import React from 'react'
import './Comites.scss'

import Accordion from './components/Accordion/Accordion.tsx'

const Comites = () => {
    return (
        <div className='comites'>
            <div className="container">
                <h1>Les postes exécutifs</h1>
                <Accordion title='Président' description="Le rôle du président est crucial pour la gestion de l'association. Il est responsable de définir sa vision, de superviser l'ensemble de l'organisation et de veiller au bon fonctionnement de toutes les activités. Le président doit également s'assurer que les membres du comité et les bénévoles collaborent de manière efficace pour atteindre les objectifs de l'association. Il doit encourager la communication ouverte et constructive entre les membres et les participants afin de maintenir une ambiance positive et motivante pour tous. Le président doit donc mettre à profit ses compétences en leadership pour favoriser un environnement harmonieux au sein de l'association."/>

                <Accordion title='Secrétaire' description="Le rôle de la secrétaire est de soutenir la gestion efficace de l'association en structurant les réunions de l'exécutif, en produisant des comptes-rendus précis et en assurant le suivi des actions et des décisions prises lors des réunions. Pour remplir ses responsabilités de manière efficace, la secrétaire doit être très organisée, capable de gérer plusieurs tâches en même temps, et avoir une excellente gestion du temps. De plus, la secrétaire doit être en mesure de gérer les communications via différents canaux tels que les messages Facebook, les messages Instagram, les courriels, etc. Enfin, elle doit veiller à ce que les réservations de salle soient effectuées en temps opportuns et que les activités de l'association puissent se dérouler dans des conditions optimales."/>

                <Accordion title='Trésorier' description="Le rôle du trésorier est crucial pour la santé financière de l'association. Il doit veiller à une gestion intelligente du budget de l'association en établissant des prévisions budgétaires et en suivant les dépenses. Le trésorier doit avoir de solides compétences en gestion financière et avoir une bonne connaissance des différents mécanismes de financement disponibles pour les associations. En outre, il doit trouver des sources de financement, telles que des subventions, des dons, des levées de fonds ou des partenariats avec des entreprises locales. Cette mission est essentielle pour soutenir le développement et la croissance financière de l'association sur le long terme."/>

                <Accordion title="Comité da'wah" description="Se donne la vocation de créer un support à la communauté étudiante sur le campus dans sa quête de spiritualité et se donne comme mandat de sensibiliser les gens au message de l'islam. Ainsi, le comité da'wah offre du matériel (livres, corans, pamphlets), des conférences et des ateliers sur divers thèmes islamiques."/>

                <Accordion title='Vice-président humanitaire' description="Le vice-président de projet humanitaire est un membre clé de l'association qui est chargé de planifier et d'exécuter des projets humanitaires et communautaires.  Le vice-président de projet humanitaire doit organiser et superviser tous les aspects des projets humanitaires et communautaires de l'association. Il doit travailler en étroite collaboration avec les membres de l'association et bénévoles pour s'assurer que les projets sont exécutés de manière efficace. Il est également responsable de la mise en place de partenariats avec des organismes humanitaires et caritatifs. Il doit rechercher des partenaires potentiels, établir des contacts, et négocier les termes et les conditions des partenariats."/>

                <Accordion title='Vice-présidents activités' description="Les deux vice-présidents des activités sont responsables de la gestion et de l'organisation d'activités sociales variées pour la communauté étudiante. Ils doivent veiller au maintien d'une communauté étudiante solidaire et engagée en proposant des événements amusants qui permettent de renforcer les liens entre les étudiants. En outre, les vice-présidents des activités doivent veiller à ce que les événements organisés soient propices à la création de nouveaux contacts et relations entre les étudiants, tout en encourageant la participation active des associations étudiantes. Pour se faire, les vice-présidents doivent user de leur créativité et travailler en étroite collaboration avec les membres de l'association pour identifier les besoins et les intérêts de la communauté étudiante. Ils doivent travailler à créer un environnement chaleureux et accueillant où tous les étudiants se sentent à l'aise de participer et de s'impliquer."/>

                <Accordion title='Vice-président communication' description="Le vice-président communication est le garant de la visibilité de l'association auprès de la communauté. Il est responsable de la promotion et de la publicité des activités de l’association à travers différents canaux de communication tels que Facebook, la chaîne WhatsApp et Instagram. Un de ses objectifs est également de s'assurer que l'association dispose de matériel photographique de qualité pour promouvoir ses activités et son image auprès du public. En utilisant les images et vidéos prises lors des événements, le vice-président des communications va mettre en œuvre sa créativité et son ingéniosité pour créer du contenu publicitaire efficace pour l'association. Il pourra notamment utiliser des plateformes telles que TikTok pour produire des vidéos engageantes et partager des moments forts de l'association avec la communauté. De plus, il peut utiliser ces images pour créer des affiches, des dépliants ou encore des bannières pour le site web de l'association."/>

                <Accordion title='Vice-président externe' description="Le vice-président externe est responsable de maintenir une communication régulière avec d'autres associations, en particulier lorsqu'il s'agit d'organiser des activités ou des projets collaboratifs. Il doit établir des partenariats avec d'autres organisations étudiantes ou communautaires afin de renforcer la présence et l'impact de l'association dans la communauté. Il doit également veiller à ce que l'association soit représentée lors d'événements organisés par d'autres associations ou organismes, afin de développer des relations de confiance et de coopération."/>
            </div>
        </div>
    )
}

export default Comites